export const LIST_PRODUCT = 'LIST_PRODUCT';
export const DETAIL_PRODUCT = 'DETAIL_PRODUCT';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const RELATED_PRODUCTS = 'RELATED_PRODUCTS';
export const LIST_CATEGORIES = 'LIST_CATEGORIES';